name: Google Cloud Authentication

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud credentials
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/google-credentials.json
      
    - name: Authenticate Google Cloud
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/google-credentials.json
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/google-credentials.json

    - name: Verify authentication
      run: gcloud auth list
